export type LegalDocument={title:string;summary:string;sections:{heading:string;body:string[]}[]};
export const legalDocuments:Record<string,LegalDocument>={
  terms:{title:"Terms of Service",summary:"The rules for accessing Mahadum as a learner, creator, affiliate, or administrator.",sections:[
    {heading:"1. Agreement and eligibility",body:["By creating an account or using Mahadum, you agree to these Terms and the policies referenced here. You must be legally capable of entering a contract and provide accurate account information.","You are responsible for your account, credentials, activity, and compliance with laws that apply to you."]},
    {heading:"2. Marketplace role",body:["Mahadum provides technology for creators to publish learning products and for learners to discover and purchase them. Unless explicitly stated, creators are responsible for their course claims, materials, and delivery.","We may review, reject, remove, suspend, or restrict content or accounts to protect learners, creators, the platform, or legal compliance."]},
    {heading:"3. Purchases and access",body:["Prices and currencies are shown before checkout. Access is granted only after payment is verified. You may not share paid access, bypass course restrictions, or misuse downloadable resources.","Refunds are governed by the Refund Policy. Payment reversals, fraud, or chargebacks may result in access suspension while a transaction is investigated."]},
    {heading:"4. Acceptable use",body:["Do not infringe intellectual property, upload malware, harass users, manipulate reviews or referrals, commit fraud, scrape protected data, probe security, or use Mahadum unlawfully.","You may report suspected abuse to ngbridz@gmail.com."]},
    {heading:"5. Intellectual property",body:["Creators retain ownership of their original content and grant Mahadum a worldwide, non-exclusive licence to host, display, market, and deliver it for operating the marketplace. Learners receive a limited, personal, non-transferable licence to use purchased materials.","Mahadum branding, software, interface, and platform materials remain protected. No ownership transfers except where expressly stated."]},
    {heading:"6. Availability and liability",body:["We work to keep Mahadum reliable but do not guarantee uninterrupted access. To the extent permitted by law, Mahadum is not liable for indirect, incidental, special, or consequential losses.","Nothing in these Terms excludes rights or liabilities that cannot legally be excluded."]},
    {heading:"7. Suspension, termination, and changes",body:["We may suspend or terminate accounts for violations, fraud, security risks, legal obligations, or material harm. You may stop using Mahadum at any time, subject to unresolved payments or obligations.","We may update these Terms prospectively. Material changes will be communicated through the platform or account email."]},
  ]},
  privacy:{title:"Privacy Policy",summary:"How Mahadum collects, uses, protects, and retains personal information.",sections:[
    {heading:"1. Information we collect",body:["We collect account details, profile information, creator submissions, enrollments, progress, reviews, referrals, transaction references, support messages, device data, and security logs.","Payment providers process card or bank details. Mahadum should retain only necessary provider references and verification records rather than raw payment credentials."]},
    {heading:"2. Why we use information",body:["We use information to provide accounts and courses, process purchases and payouts, prevent fraud, issue certificates, support users, improve the marketplace, communicate service messages, and comply with law.","Where consent is legally required for optional marketing or analytics, users will be offered an appropriate choice."]},
    {heading:"3. Sharing",body:["Information may be shared with relevant creators, payment and infrastructure providers, professional advisers, or authorities when necessary for service delivery, safety, legal compliance, or enforcing agreements.","Mahadum does not sell personal information."]},
    {heading:"4. Security and retention",body:["We use access controls, encryption in transit, row-level database rules, audit records, and limited secret access. No system can guarantee absolute security.","Records are kept only as long as needed for service, dispute, accounting, fraud-prevention, and legal purposes, then deleted or anonymised where appropriate."]},
    {heading:"5. Your choices and rights",body:["Depending on applicable law, you may request access, correction, deletion, restriction, objection, portability, or withdrawal of consent. Some financial and security records must be retained.","Send privacy requests to ngbridz@gmail.com. Identity verification may be required before fulfilling a request."]},
    {heading:"6. International processing and updates",body:["Providers may process information in other countries with appropriate contractual and technical safeguards.","Material policy changes will be communicated through Mahadum or account email."]},
  ]},
  refunds:{title:"Refund Policy",summary:"A fair seven-day process that protects learners while accounting for consumed digital content.",sections:[
    {heading:"1. Standard window",body:["A learner may request a refund within seven calendar days after a successful payment. A request does not guarantee approval and must include a clear reason."]},
    {heading:"2. Eligibility",body:["Refunds are generally available when a course was materially misrepresented, unavailable, technically inaccessible after reasonable support, or purchased accidentally without substantial consumption.","A request may be declined where a substantial portion was completed or downloaded, a certificate was issued, access was abused or shared, the request is fraudulent, or the seven-day window passed, except where law requires otherwise."]},
    {heading:"3. Review and outcome",body:["Mahadum may review progress, access, downloads, support history, and payment status. Approved refunds are returned through the original payment method where possible.","Provider and bank processing times are outside Mahadum’s control. Course access and related certificates may be revoked after a refund."]},
    {heading:"4. How to request",body:["Submit a request from the learner transaction area or email ngbridz@gmail.com with the account email, course, transaction reference, and reason. Do not send card or banking secrets."]},
  ]},
  creators:{title:"Creator Agreement",summary:"Commercial and content terms for publishing and earning through Mahadum.",sections:[
    {heading:"1. Creator responsibilities",body:["Creators must provide accurate identity and payout information, own or properly license their materials, describe courses honestly, maintain reasonable quality, and respond to legitimate moderation or learner concerns.","Creators must not upload unlawful, unsafe, deceptive, plagiarised, discriminatory, or rights-infringing content."]},
    {heading:"2. Licence and promotion",body:["Creators retain ownership and grant Mahadum a non-exclusive worldwide licence to host, reproduce, format, display, market, and deliver submitted materials for operating and promoting the marketplace.","Mahadum may use approved creator names, images, excerpts, and course previews for marketplace promotion."]},
    {heading:"3. Revenue and settlement",body:["The baseline allocation is 70% creator, 25% Mahadum, 3% first-level affiliate, and 2% second-level affiliate. If no qualifying affiliate applies, the unused affiliate allocation is retained by Mahadum for marketplace operations.","Earnings settle after a seven-day hold. Eligible balances of at least ₦10,000 are processed on the weekly Friday payout schedule, subject to verification, fraud review, provider availability, refunds, chargebacks, taxes, and lawful deductions."]},
    {heading:"4. Moderation and removal",body:["Creator Hub access begins immediately, but courses require review before publication. Mahadum may reject, unpublish, archive, or remove courses and may suspend monetisation for policy, quality, security, or legal reasons."]},
    {heading:"5. Refunds and adjustments",body:["Refunds, chargebacks, reversals, and confirmed affiliate fraud may reduce pending or future creator balances. Mahadum will maintain auditable transaction records."]},
    {heading:"6. Ending participation",body:["Creators may stop publishing subject to existing learner access and unresolved obligations. Mahadum may terminate participation for material breach, repeated quality failure, fraud, or legal risk."]},
  ]},
  affiliates:{title:"Affiliate Terms",summary:"Rules for Mahadum’s transparent two-level referral programme.",sections:[
    {heading:"1. Participation",body:["Affiliates must use accurate identity and payout details and receive approval before commissions become payable. Participation does not create employment, partnership, or authority to bind Mahadum."]},
    {heading:"2. Commissions",body:["A qualifying first-level referral earns 3% and an eligible second-level referral earns 2% of the verified course payment. Commissions arise only after successful payment verification and remain subject to the seven-day settlement hold.","Payouts require a settled balance of at least ₦10,000 and are processed on the weekly Friday schedule."]},
    {heading:"3. Prohibited activity",body:["Self-referrals, false identities, cookie stuffing, misleading claims, spam, paid-search impersonation, forced clicks, referral loops, hidden redirects, and any fraudulent or unlawful acquisition method are prohibited."]},
    {heading:"4. Reversals and enforcement",body:["Commissions may be reversed for refunds, chargebacks, duplicated attribution, abuse, or fraud. Mahadum may withhold payments during investigation and suspend or terminate an affiliate account."]},
    {heading:"5. Programme changes",body:["Mahadum may change prospective rates, attribution rules, or programme availability with reasonable notice. Earned and valid settled commissions remain payable subject to these Terms."]},
  ]},
};
