import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {markLessonComplete} from "@/app/dashboard/actions";

type Lesson={id:string;title:string;description:string|null;video_url:string|null;duration_seconds:number|null;position:number;module_id:string};
export default async function CoursePlayer({params}:{params:Promise<{course:string;lesson:string}>}){
  const {course,lesson}=await params;const client=await createClient();if(!client)redirect("/login");const {data:{user}}=await client.auth.getUser();if(!user)redirect("/login");
  const {data:enrollment}=await client.from("enrollments").select("id,courses(title)").eq("learner_id",user.id).eq("course_id",course).maybeSingle();if(!enrollment)notFound();
  const {data:modules}=await client.from("course_modules").select("id,title,position,lessons(id,title,description,video_url,duration_seconds,position,module_id)").eq("course_id",course).order("position");
  const lessons=((modules||[]).flatMap(module=>(module.lessons||[]).map(item=>({...item,moduleTitle:module.title,modulePosition:module.position}))) as (Lesson&{moduleTitle:string;modulePosition:number})[]).sort((a,b)=>a.modulePosition-b.modulePosition||a.position-b.position);
  const active=lessons.find(item=>item.id===lesson);if(!active)notFound();const {data:progress}=await client.from("lesson_progress").select("lesson_id,completed_at").eq("enrollment_id",enrollment.id);const completed=new Set((progress||[]).filter(x=>x.completed_at).map(x=>x.lesson_id));const current=lessons.indexOf(active);const next=lessons[current+1];const previous=lessons[current-1];const percent=lessons.length?Math.round(completed.size/lessons.length*100):0;
  return <main className="player"><header><Link className="brand" href="/"><span className="brand-mark">M</span> Mahadum</Link><div>{String((enrollment.courses as {title?:string}|null)?.title||"Course")} <span>{percent}% complete</span></div><Link href="/dashboard/learner/my-learning">Exit</Link></header><div className="player-grid"><aside><h3>Course curriculum</h3>{lessons.map((item,index)=><Link className={item.id===active.id?"active":""} href={`/learn/${course}/${item.id}`} key={item.id}><span>{completed.has(item.id)?"✓":index+1}</span><div><b>{item.title}</b><small>{Math.ceil((item.duration_seconds||0)/60)} min</small></div></Link>)}</aside><section><div className="video-stage">{active.video_url?<a className="button" href={active.video_url} target="_blank" rel="noreferrer">Open lesson video</a>:<span>Video will be added by the creator</span>}</div><div className="lesson-content"><span className="overline">{active.moduleTitle} · Lesson {active.position+1}</span><h1>{active.title}</h1><p>{active.description||"No lesson notes have been added yet."}</p><div className="lesson-actions">{previous?<Link className="outline-button" href={`/learn/${course}/${previous.id}`}>← Previous</Link>:<span/>}<form action={markLessonComplete}><input type="hidden" name="enrollment_id" value={enrollment.id}/><input type="hidden" name="lesson_id" value={active.id}/><button className="button">{completed.has(active.id)?"Completed":next?"Mark complete & continue →":"Complete course"}</button></form>{next&&completed.has(active.id)&&<Link className="text-link" href={`/learn/${course}/${next.id}`}>Next →</Link>}</div></div></section></div></main>
}
