"use client";

import { useMemo, useState } from "react";
import { grantCourseAccess, setUserSuspension, updateUserRoles } from "@/app/dashboard/actions";
import type { Row } from "@/lib/dashboard";

const value=(input:unknown)=>typeof input==="string"?input:"";
const roles=(row:Row)=>Array.isArray(row.user_roles)?(row.user_roles as Row[]).map(item=>value(item.role)):[];
const joined=(input:unknown)=>input?new Intl.DateTimeFormat("en-NG",{dateStyle:"medium"}).format(new Date(String(input))):"—";

export function AdminUsers({users,courses,currentUserId}:{users:Row[];courses:Row[];currentUserId:string}){
  const [query,setQuery]=useState("");const [role,setRole]=useState("all");const [status,setStatus]=useState("all");
  const filtered=useMemo(()=>users.filter(user=>{const userRoles=roles(user);const matchesText=`${value(user.full_name)} ${value(user.email)}`.toLowerCase().includes(query.toLowerCase());return matchesText&&(role==="all"||userRoles.includes(role))&&(status==="all"||(status==="suspended")===Boolean(user.is_suspended));}),[users,query,role,status]);
  const counts={total:users.length,learners:users.filter(x=>roles(x).includes("learner")).length,creators:users.filter(x=>roles(x).includes("creator")).length,suspended:users.filter(x=>Boolean(x.is_suspended)).length};
  return <div className="dashboard-page admin-users-page">
    <div className="page-head"><div><h1>Users</h1><p>Manage Mahadum accounts, roles, and access.</p></div></div>
    <div className="metric-grid user-metrics"><article className="metric-card"><span>Total users</span><strong>{counts.total}</strong></article><article className="metric-card"><span>Learners</span><strong>{counts.learners}</strong></article><article className="metric-card"><span>Creators</span><strong>{counts.creators}</strong></article><article className="metric-card"><span>Suspended</span><strong>{counts.suspended}</strong></article></div>
    <section className="panel admin-users-panel"><div className="admin-user-tools"><label><span>Search users</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Name or email"/></label><label><span>Role</span><select value={role} onChange={event=>setRole(event.target.value)}><option value="all">All roles</option><option value="learner">Learners</option><option value="creator">Creators</option><option value="admin">Administrators</option></select></label><label><span>Status</span><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option></select></label></div>
      <div className="admin-user-header"><span>User</span><span>Roles</span><span>Joined</span><span>Status</span><span>Actions</span></div>
      <div className="admin-user-list">{filtered.length===0?<div className="empty-state"><b>No matching users</b><p>Try changing your search or filters.</p></div>:filtered.map(user=>{const userRoles=roles(user);const suspended=Boolean(user.is_suspended);const own=user.id===currentUserId;return <article className="admin-user-row" key={value(user.id)}><span className="user-avatar">{value(user.full_name).split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()||"U"}</span><div className="admin-user-identity"><b>{value(user.full_name)||"Unnamed user"}</b><small>{value(user.email)||"No email"}</small></div><div className="admin-role-list">{userRoles.map(item=><span key={item}>{item}</span>)}</div><span className="admin-joined"><small>Joined</small>{joined(user.created_at)}</span><span className={`status ${suspended?"rejected":"active"}`}>{suspended?"suspended":"active"}</span><div className="admin-user-actions"><details><summary>Manage</summary><div className="admin-user-menu"><form action={grantCourseAccess}><input type="hidden" name="user_id" value={value(user.id)}/><b>Unlock a course</b><small>Grant access without requiring payment.</small><label className="admin-course-grant-label">Course<select name="course_id" required defaultValue=""><option value="" disabled>Select a published course</option>{courses.map(course=><option value={value(course.id)} key={value(course.id)}>{value(course.title)}</option>)}</select></label><button className="button" disabled={courses.length===0}>Unlock course</button></form><form action={updateUserRoles}><input type="hidden" name="user_id" value={value(user.id)}/><b>Account roles</b><label><input type="checkbox" name="learner" defaultChecked={userRoles.includes("learner")}/> Learner</label><label><input type="checkbox" name="creator" defaultChecked={userRoles.includes("creator")}/> Creator</label><button className="outline-button">Save roles</button></form>{!own?<form action={setUserSuspension}><input type="hidden" name="user_id" value={value(user.id)}/><input type="hidden" name="suspended" value={String(!suspended)}/><button className={suspended?"outline-button":"danger-button"}>{suspended?"Restore access":"Suspend user"}</button></form>:<small>Your administrator account</small>}</div></details></div></article>})}</div>
    </section>
  </div>;
}
