"use client";

import Link from "next/link";
import { useState } from "react";

type AffiliateCourse = { id:string;title:string;slug:string;shortDescription:string;priceMinor:number;currency:string;affiliateBonusPercent:number;salesCount:number };
const money=(minor:number,currency:string)=>new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format(minor/100);

export function AffiliateCourseLinks({code,courses,siteUrl,baseCommissionPercent}:{code:string;courses:AffiliateCourse[];siteUrl:string;baseCommissionPercent:number}){
  const [copied,setCopied]=useState<string|null>(null);
  async function copy(course:AffiliateCourse){const url=`${siteUrl}/courses/${encodeURIComponent(course.slug)}?ref=${encodeURIComponent(code)}`;await navigator.clipboard.writeText(url);setCopied(course.id);window.setTimeout(()=>setCopied(current=>current===course.id?null:current),2000)}
  async function copyNetworkLink(){const url=`${siteUrl}/signup?ref=${encodeURIComponent(code)}`;await navigator.clipboard.writeText(url);setCopied("affiliate-network");window.setTimeout(()=>setCopied(current=>current==="affiliate-network"?null:current),2000)}
  return <><section className="panel affiliate-links-panel"><div className="panel-head"><div><h3>Refer other affiliates</h3><p>Anyone who creates an account through this link joins your affiliate network as a level-two referral.</p></div><button className="button" type="button" data-async-action onClick={copyNetworkLink}>{copied==="affiliate-network"?"Copied":"Copy affiliate referral link"}</button></div></section><section className="panel affiliate-links-panel"><div className="panel-head"><div><h3>Best-selling courses</h3><p>Courses are ranked by completed sales so your strongest opportunities appear first.</p></div></div>{courses.length===0?<div className="empty-state"><b>No published courses available</b><p>Links will appear here as soon as a course is published.</p></div>:<div className="affiliate-course-list">{courses.map((course,index)=>{const href=`/courses/${course.slug}?ref=${encodeURIComponent(code)}`;const commission=baseCommissionPercent+course.affiliateBonusPercent;return <article className="affiliate-course-row" key={course.id}><div>{index===0&&course.salesCount>0?<span className="affiliate-bestseller-badge">#1 Best seller</span>:null}<h4>{course.title}</h4><p>{course.shortDescription}</p><small>{course.salesCount} {course.salesCount===1?"sale":"sales"} · {money(course.priceMinor,course.currency)} · <b>{commission}% commission</b>{course.affiliateBonusPercent>0?` (+${course.affiliateBonusPercent}% creator bonus)`:""}</small></div><div className="affiliate-link-actions"><Link className="outline-button" href={href}>Open link</Link><button className="button" type="button" data-async-action onClick={()=>copy(course)}>{copied===course.id?"Copied":"Copy affiliate link"}</button></div></article>})}</div>}</section></>;
}
