import Link from "next/link";
import { activity, lessons, metrics } from "@/lib/demo-data";

export function DashboardContent({ role, section }: { role: string; section: string }) {
  if (section === "course-builder") return <div className="dashboard-page"><PageHead title="Course builder" subtitle="Create a clear, valuable learning experience." action="Save draft"/><div className="builder-grid"><section className="panel"><h3>Course details</h3><label>Course title<input defaultValue="Build your creative confidence" /></label><label>Description<textarea defaultValue="A practical framework for doing your best creative work consistently." /></label><div className="form-row"><label>Category<select defaultValue="Design"><option>Design</option><option>Business</option><option>Technology</option></select></label><label>Price<input defaultValue="18500" type="number" /></label></div></section><section className="panel"><h3>Curriculum</h3>{lessons.map((lesson,i)=><div className="lesson-row" key={lesson}><span>{i+1}</span><div><b>{lesson}</b><small>{i===0?"Free preview":"Video lesson"}</small></div><button aria-label={`Edit ${lesson}`}>Edit</button></div>)}<button className="outline-button">+ Add lesson</button></section></div></div>;
  if (section === "my-learning") return <div className="dashboard-page"><PageHead title="Keep learning" subtitle="Pick up where you left off." action="Explore courses"/><div className="learning-grid">{activity.slice(0,3).map((item,i)=><article className="learning-card" key={item.title}><div className={`learning-cover cover-${i+1}`}><span>{42+i*18}%</span></div><div><small>IN PROGRESS</small><h3>{item.title}</h3><div className="progress"><span style={{width:`${42+i*18}%`}}/></div><Link href="/learn/brand-identity/lesson-1">Continue learning →</Link></div></article>)}</div></div>;
  if (section === "certificates") return <div className="dashboard-page"><PageHead title="Certificates" subtitle="Proof of the skills you have earned."/><div className="certificate-sheet"><span className="brand-mark">M</span><small>CERTIFICATE OF COMPLETION</small><h2>Professional Brand Strategy</h2><p>This certifies that</p><h3>Alex Morgan</h3><p>successfully completed the course on July 18, 2026.</p><div><b>Amara Okafor</b><b>MAH-26-10482</b></div></div></div>;
  if (["users","courses","creators","learners","affiliates","finance","audit-log"].includes(section)) return <div className="dashboard-page"><PageHead title={section.replaceAll("-"," ")} subtitle={`Manage platform ${section.replaceAll("-"," ")} safely and efficiently.`} action={`Add ${section.replaceAll("-"," ")}`}/><section className="panel table-panel"><div className="table-tools"><input placeholder={`Search ${section}...`}/><button className="outline-button">Filter</button></div><div className="data-table">{activity.map((item,i)=><div className="data-row" key={item.title}><span className="user-avatar">{item.title.split(" ").map(w=>w[0]).slice(0,2).join("")}</span><div><b>{item.title}</b><small>{item.detail}</small></div><span>{i%2?"Learner":"Creator"}</span><span className={`status ${item.status.toLowerCase().replace(" ","-")}`}>{item.status}</span><button aria-label={`Actions for ${item.title}`}>•••</button></div>)}</div></section></div>;
  return <div className="dashboard-page"><PageHead title={section === "overview" ? `Good morning, ${role === "admin" ? "Admin" : "Amara"}` : section.replaceAll("-"," ")} subtitle={role === "learner" ? "Continue your learning journey." : "Here is what is happening across your work."} action={role === "creator" ? "Create course" : role === "admin" ? "Export report" : undefined}/><div className="metric-grid">{metrics.map(metric=><article className="metric-card" key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.change} from last month</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="overline">Performance</span><h3>Revenue overview</h3></div><select aria-label="Period"><option>Last 6 months</option></select></div><div className="chart" aria-label="Revenue trending upward"><i style={{height:"25%"}}/><i style={{height:"40%"}}/><i style={{height:"34%"}}/><i style={{height:"58%"}}/><i style={{height:"66%"}}/><i style={{height:"88%"}}/></div></section><section className="panel"><div className="panel-head"><h3>Recent activity</h3><a href="#all">View all</a></div>{activity.map(item=><div className="activity-row" key={item.title}><span>↗</span><div><b>{item.title}</b><small>{item.detail}</small></div><strong>{item.value}</strong></div>)}</section></div></div>;
}

function PageHead({title,subtitle,action}:{title:string;subtitle:string;action?:string}){return <div className="page-head"><div><h1>{title}</h1><p>{subtitle}</p></div>{action&&<button className="button button-small">{action}</button>}</div>}
